// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqydj9A0GlZMAjBxOpnZBzfuC22dpUc6g',
    appId: '1:692135371948:web:88e30cf5ee3f0dd7e9eb09',
    messagingSenderId: '692135371948',
    projectId: 'shopping-list-app-c5e24',
    authDomain: 'shopping-list-app-c5e24.firebaseapp.com',
    storageBucket: 'shopping-list-app-c5e24.appspot.com',
    measurementId: 'G-JLNXDR9GBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLt3ziB9gTE8U9pRyg9QZHRW6LcwTUJrE',
    appId: '1:692135371948:android:78e5b328fbea2569e9eb09',
    messagingSenderId: '692135371948',
    projectId: 'shopping-list-app-c5e24',
    storageBucket: 'shopping-list-app-c5e24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUqA9kLAQ2Ju-kCr673L5SgRXvTRtmRG8',
    appId: '1:692135371948:ios:e68940b081fad420e9eb09',
    messagingSenderId: '692135371948',
    projectId: 'shopping-list-app-c5e24',
    storageBucket: 'shopping-list-app-c5e24.appspot.com',
    iosBundleId: 'com.example.checkBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUqA9kLAQ2Ju-kCr673L5SgRXvTRtmRG8',
    appId: '1:692135371948:ios:e68940b081fad420e9eb09',
    messagingSenderId: '692135371948',
    projectId: 'shopping-list-app-c5e24',
    storageBucket: 'shopping-list-app-c5e24.appspot.com',
    iosBundleId: 'com.example.checkBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqydj9A0GlZMAjBxOpnZBzfuC22dpUc6g',
    appId: '1:692135371948:web:6b8d433b4deec305e9eb09',
    messagingSenderId: '692135371948',
    projectId: 'shopping-list-app-c5e24',
    authDomain: 'shopping-list-app-c5e24.firebaseapp.com',
    storageBucket: 'shopping-list-app-c5e24.appspot.com',
    measurementId: 'G-GFF1N4H7VM',
  );

}